repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/ambv/black
    rev: 23.9.1
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: migrations/
        args:
          - --line-length=100
  - repo: local
    hooks:
      - id: build-from-templates
        name: build-from-templates
        entry: python build.py
        language: system
        pass_filenames: false
